"""Blender compositor: masked shadow lift, preserving pixel layout and source image."""
import bpy
from pathlib import Path
out=Path('outputs/eclairage-v7').resolve();s=bpy.context.scene;s.use_nodes=True;s.render.engine='BLENDER_EEVEE_NEXT';s.render.resolution_x=5000;s.render.resolution_y=4000;s.render.resolution_percentage=100;s.view_settings.view_transform='Standard';s.view_settings.look='None';s.view_settings.exposure=0;s.view_settings.gamma=1;s.render.image_settings.file_format='PNG';s.render.image_settings.color_mode='RGB';s.render.image_settings.color_depth='8';s.render.filepath=str(out/'donnees/orthophoto-ombres-attenuees.png')
ns=s.node_tree.nodes;ls=s.node_tree.links;ns.clear();source=ns.new('CompositorNodeImage');source.name='SOURCE — orthophoto 2025 intacte';source.image=bpy.data.images.load(str(Path('outputs/terrain-hybride-v6/donnees/orthophoto-2025-2m.jpg').resolve()));source.image.pack();source.location=(-600,200)
bw=ns.new('CompositorNodeRGBToBW');bw.name='Luminance en lumière linéaire';bw.location=(-400,-50);ls.new(source.outputs['Image'],bw.inputs[0]);mask=ns.new('CompositorNodeMapRange');mask.name='Masque des tons sombres — 0,008 à 0,085';mask.location=(-200,-50);mask.use_clamp=True;mask.inputs[1].default_value=.008;mask.inputs[2].default_value=.085;mask.inputs[3].default_value=1;mask.inputs[4].default_value=0;ls.new(bw.outputs[0],mask.inputs[0]);mix=ns.new('CompositorNodeMixRGB');mix.name='Atténuation progressive — gain maximal 1,75';mix.blend_type='MULTIPLY';mix.location=(50,200);mix.inputs[2].default_value=(1.75,1.75,1.75,1);ls.new(source.outputs['Image'],mix.inputs[1]);ls.new(mask.outputs[0],mix.inputs[0]);comp=ns.new('CompositorNodeComposite');comp.location=(300,200);ls.new(mix.outputs[0],comp.inputs['Image'])
# A camera satisfies Blender's render operator; the composite uses only the source image.
data=bpy.data.cameras.new('Caméra technique');cam=bpy.data.objects.new('Caméra technique',data);s.collection.objects.link(cam);s.camera=cam
bpy.ops.wm.save_as_mainfile(filepath=str(out/'correction-orthophoto.blend'),compress=True);bpy.ops.render.render(write_still=True);print('ORTHOPHOTO_CORRECTED',flush=True)
